# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c432124fda432d1966fc3cf592ea1a0b049b402695e8e735586d3dc7d31d4a9321280861a4d3aadd10a8bdf092006268f532ef26eeb85baeefa84d201dc0269f

test:
  secret_key_base: 90d77565a2204af61ceb800e39c0dbd8254b07c92f5abb29c387c19c88a679ca20977e41ce11661cab3d9d09bbdb33698c5bd2520a488e79d12c35753995c8df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
